name: Publish Container image
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  push_to_registry:
    name: Push Container image to GitHub Packages
    runs-on: ubuntu-18.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Create unique identifier
        id: ident
        run: |
          DATE=`date -u +"%Y-%m-%d_%H-%M-%S"`
          echo "::set-output name=date::$DATE"
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/${{ steps.ident.outputs.date }}
          tag_with_ref: true
          context: .
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
